# Generated by Django 6.0.3 on 2026-04-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailverificationtoken_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Waste', 'Waste Management'), ('Parking', 'Parking Issues'), ('Infrastructure', 'Infrastructure Damage'), ('Security', 'Security Incident'), ('Other', 'Other')], max_length=50),
        ),
    ]
